spring.application.name=Online Hackthon Management System
#----ONLY UNCOMMIT IN PRODUCTION----------
#spring.config.import=aws-secretsmanager:prod/springboot/hackathon
spring.cloud.aws.region.static=ap-south-1
#-----------------------------------
#----USE IN LOCAL BRANCH----------
spring.config.import=optional:file:.env[.properties]
#--------------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.username=${MYSQL_ROOT_NAME}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=900000000
security.jwt.refresh-token.expiration-time=604800000
logging.level.org.springframework.security=DEBUG
#twilio.account-sid=${TWILIO_ACCOUNT_SID}
#twilio.auth-token=${TWILIO_AUTH_TOKEN}
#twilio.verification-sid=${TWILIO_VERIFICATION_SSID}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY}
jaas.app-id=${JASS_APP_ID}
jaas.api-key=${JASS_API_KEY}
jaas.private-key-location=${JASS_PRIVATE_KEY}
#---------------- Enable in Development-----------
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
